all:
  hosts:
    ec2-54-243-235-6.compute-1.amazonaws.com:
      ansible_ssh_private_key_file: "/Users/aaronharlap/Documents/aws/aaron-ec2-key-east1.pem"
      ansible_ssh_user: "ubuntu"
      ansible_python_interpreter: "/usr/bin/python3"
      determined_path: /home/ubuntu/repos/temp/determined/
